apiVersion: v1
kind: Service
metadata:
  name: demo-iris-service
  labels:
    app: demo-iris
spec:
  type: LoadBalancer
  selector:
    app: demo-iris
  ports:
    - protocol: TCP
      port: 80          # external port
      targetPort: 8200  # container port (from your FastAPI app)
