name: CD - Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 1: Decode and authenticate to Google Cloud
    - name: Decode and authenticate to Google Cloud
      run: |
        echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > $HOME/gcp-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set compute/region ${{ secrets.GCP_REGION }}


    - name: Install kubectl and GKE auth plugin
      run: |
        sudo apt-get update -y
        sudo apt-get install -y apt-transport-https ca-certificates gnupg curl

        # Add Google Cloud SDK distribution URI as a package source
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | \
          sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list

        # Import the Google Cloud public key (modern method)
        curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
          sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg

        # Update and install
        sudo apt-get update -y
        sudo apt-get install -y google-cloud-sdk google-cloud-sdk-gke-gcloud-auth-plugin kubectl



    # Step 3: Get cluster credentials
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials demo-log-ml-cluster --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}

    # Step 4: Deploy Kubernetes manifests
    - name: Deploy to GKE
      run: |
        kubectl apply -f kubernetes/deployment.yaml --validate=false
        kubectl apply -f kubernetes/service.yaml --validate=false
        kubectl apply -f kubernetes/hpa.yaml --validate=false

    # Step 5: Verify deployment
    - name: Verify Deployment
      run: |
        kubectl get pods
        kubectl get svc
        kubectl get hpa
